//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SmtpMailClient.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("SmtpMailClient.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap add {
            get {
                object obj = ResourceManager.GetObject("add", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap delete {
            get {
                object obj = ResourceManager.GetObject("delete", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap email_to_friend_ico {
            get {
                object obj = ResourceManager.GetObject("email-to-friend-ico", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap email_to_friend_png {
            get {
                object obj = ResourceManager.GetObject("email-to-friend-png", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap email_to_friend_santa {
            get {
                object obj = ResourceManager.GetObject("email-to-friend-santa", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to About {0}.
        /// </summary>
        public static string RES_ID_About {
            get {
                return ResourceManager.GetString("RES_ID_About", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Computername: .
        /// </summary>
        public static string RES_ID_Computername {
            get {
                return ResourceManager.GetString("RES_ID_Computername", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The language change will take full effect the next time you start the program..
        /// </summary>
        public static string RES_ID_CultureChange {
            get {
                return ResourceManager.GetString("RES_ID_CultureChange", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to E-Mail sent.
        /// </summary>
        public static string RES_ID_MailSent {
            get {
                return ResourceManager.GetString("RES_ID_MailSent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to     Mail size: .
        /// </summary>
        public static string RES_ID_MailSize {
            get {
                return ResourceManager.GetString("RES_ID_MailSize", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to E-Mail too big..
        /// </summary>
        public static string RES_ID_MailTooBig {
            get {
                return ResourceManager.GetString("RES_ID_MailTooBig", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Missing value for maximal Mailsize..
        /// </summary>
        public static string RES_ID_NoMaxMailSize {
            get {
                return ResourceManager.GetString("RES_ID_NoMaxMailSize", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Missing receiver address..
        /// </summary>
        public static string RES_ID_NoReceiverAddr {
            get {
                return ResourceManager.GetString("RES_ID_NoReceiverAddr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Missing sender address..
        /// </summary>
        public static string RES_ID_NoSenderAddr {
            get {
                return ResourceManager.GetString("RES_ID_NoSenderAddr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Missing SMTP port..
        /// </summary>
        public static string RES_ID_NoSmtpPort {
            get {
                return ResourceManager.GetString("RES_ID_NoSmtpPort", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Missing SMTP server address..
        /// </summary>
        public static string RES_ID_NoSmtpServer {
            get {
                return ResourceManager.GetString("RES_ID_NoSmtpServer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Receiver address has wrong format..
        /// </summary>
        public static string RES_ID_ReceiverFormat {
            get {
                return ResourceManager.GetString("RES_ID_ReceiverFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sender address has wrong format..
        /// </summary>
        public static string RES_ID_SenderFormat {
            get {
                return ResourceManager.GetString("RES_ID_SenderFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sending E-Mail.......
        /// </summary>
        public static string RES_ID_SendingMail {
            get {
                return ResourceManager.GetString("RES_ID_SendingMail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to UNC Path not supported..
        /// </summary>
        public static string RES_ID_UNCpathNot {
            get {
                return ResourceManager.GetString("RES_ID_UNCpathNot", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Version {0}.
        /// </summary>
        public static string RES_ID_Version {
            get {
                return ResourceManager.GetString("RES_ID_Version", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap santa_hat_icon {
            get {
                object obj = ResourceManager.GetObject("santa-hat-icon", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
    }
}
